# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1412423083);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1412422843);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1412423203);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1412422963);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140923175406");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 748);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20140923175406");
user_pref("browser.startup.homepage_override.mstone", "32.0.3");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4,\"addons\":4}");
user_pref("browser.taskbar.lastgroupid", "C1DF0C3AAE7578AD");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("browser.uitour.whitelist.add.340", "");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1412365905331");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1412422785413");
user_pref("datareporting.policy.firstRunTime", "1412279505331");
user_pref("datareporting.sessions.current.activeTicks", 18);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 714);
user_pref("datareporting.sessions.current.main", 1);
user_pref("datareporting.sessions.current.sessionRestored", 758);
user_pref("datareporting.sessions.current.startTime", "1412422722572");
user_pref("datareporting.sessions.current.totalTime", 512);
user_pref("datareporting.sessions.currentIndex", 5);
user_pref("datareporting.sessions.previous.0", "{\"s\":1412279504713,\"a\":6,\"t\":31,\"c\":true,\"m\":64,\"fp\":2068,\"sr\":3615}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1412279553679,\"a\":8,\"t\":38,\"c\":true,\"m\":64,\"fp\":604,\"sr\":648}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1412279731854,\"a\":11,\"t\":72,\"c\":true,\"m\":523,\"fp\":1094,\"sr\":1255}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1412280151649,\"a\":5,\"t\":31,\"c\":true,\"m\":374,\"fp\":832,\"sr\":952}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1412422698177,\"a\":5,\"t\":22,\"c\":true,\"m\":60,\"fp\":1266,\"sr\":1359}");
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_TOOLBOX_OPENED_PER_USER_FLAG\":\"32.0.3\",\"DEVTOOLS_WEBCONSOLE_OPENED_PER_USER_FLAG\":\"32.0.3\"}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.autoAuth.lastAuthJSON", "{\"A username and password are being requested by http://localhost:8080. The site says: \\\"Users\\\"\":1412422798}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "autoauth%40efinke.com:2.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:32.0.3");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"wrc@avast.com\":{\"descriptor\":\"C:\\\\Kamat\\\\Programs\\\\Avast\\\\WebRep\\\\FF\",\"mtime\":1412339558652,\"rdfTime\":1412339526947}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Kamat\\\\Programs\\\\Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1411722153035,\"rdfTime\":1411526204000}}},{\"name\":\"app-profile\",\"addons\":{\"autoauth@efinke.com\":{\"descriptor\":\"C:\\\\Users\\\\Iiro\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\iccy93ti.Robot\\\\extensions\\\\autoauth@efinke.com.xpi\",\"mtime\":1412422722691}}}]");
user_pref("extensions.lastAppVersion", "32.0.3");
user_pref("extensions.lastPlatformVersion", "32.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20140923175406");
user_pref("gecko.mstone", "32.0.3");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("network.automatic-ntlm-auth.trusted-uris", "localhost:8080/libtek");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.privacy.disable_button.view_passwords", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.autologin.proxy", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1412422722);
user_pref("toolkit.telemetry.previousBuildID", "20140923175406");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
